######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 10 16:36:04 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bola.h mainwindow.h
SOURCES += bola.cpp main.cpp mainwindow.cpp
