######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 14 19:42:17 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bola.h mainwindow.h
SOURCES += bola.cpp main.cpp mainwindow.cpp
