######################################################################
# Automatically generated by qmake (2.01a) Tue Jan 21 18:39:16 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bola.h dialogoConfiguracion.h mainwindow.h
FORMS += DialogoConfiguracion.ui
SOURCES += bola.cpp dialogoConfiguracion.cpp main.cpp mainwindow.cpp
